version: "3.9"

volumes:
  mongodata:

services:
  api:
    build:
      context: ./api
    environment:
      - DB_CONNECTION=mongodb://db/mbp
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    depends_on:
      - db
  
  db:
    image: mongo:4.2.18
    environment:
      - MONGO_INITDB_DATABASE=mbp
    volumes:
      # - ./db-seed.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - mongodata:/data/db